# Generated by Django 3.1.12 on 2025-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMMReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('oe_name', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('uploaded_from', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CMM Report',
                'verbose_name_plural': 'CMM Reports',
            },
        ),
    ]
